import "./globals.css";
import localFont from "next/font/local";
import { classNames } from "../utils/class_names";

const manrope = localFont({
  src: "../public/fonts/Manrope.ttf",
  variable: "--font-sans",
});

const zighead = localFont({
  src: "../public/fonts/Zighead.otf",

  variable: "--font-title",
});
export const metadata = {
  title: "Stan Husson - Front-end & UX/UI/3D Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="bg-gradient-to-r from-content-grey_800 via-content-grey_900 to-content-grey_900 [&::-webkit-scrollbar]:hidden [-ms-overflow-style:'none'] [scrollbar-width:'none']"
    >
      <body
        className={classNames(
          manrope.variable,
          zighead.variable,
          "font-sans flex flex-col  text-content-grey_100"
        )}
      >
        {children}
      </body>
    </html>
  );
}
